# Generated by Django 4.2 on 2025-11-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_labresults_cod_ing_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresults',
            name='cedula',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
